# Generated by Django 3.0.6 on 2020-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200704_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='topic',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
