# Generated by Django 3.0.6 on 2020-07-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
